/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--healix-primary-50)',
          100: 'var(--healix-primary-100)',
          200: 'var(--healix-primary-200)',
          300: 'var(--healix-primary-300)',
          400: 'var(--healix-primary-400)',
          500: 'var(--healix-primary-500)',
          600: 'var(--healix-primary-600)',
          700: 'var(--healix-primary-700)',
          800: 'var(--healix-primary-800)',
          900: 'var(--healix-primary-900)',
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          light: 'var(--color-primary-light)',
          soft: 'var(--color-primary-soft)',
          dark: 'var(--healix-primary-800)',
        },
        secondary: {
          50: 'var(--healix-secondary-50)',
          100: 'var(--healix-secondary-100)',
          200: 'var(--healix-secondary-200)',
          300: 'var(--healix-secondary-300)',
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          active: 'var(--color-secondary-active)',
        },
        accent: {
          100: 'var(--healix-accent-100)',
          300: 'var(--healix-accent-300)',
          500: 'var(--healix-accent-500)',
          600: 'var(--healix-accent-600)',
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          soft: 'var(--color-accent-soft)',
        },
        background: 'var(--color-background)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          muted: 'var(--color-surface-muted)',
          elevated: 'var(--color-surface-elevated)',
          dark: 'var(--color-surface-dark)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
          brand: 'var(--color-text-brand)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          subtle: 'var(--color-border-subtle)',
          strong: 'var(--color-border-strong)',
          focus: 'var(--color-border-focus)',
        },
        healix: {
          dark: '#075A46',
          DEFAULT: '#075A46',
          green: '#0E745B',
          secondary: '#0E745B',
          lime: '#94D126',
          accent: '#94D126',
          soft: '#EAF4EF',
          pale: '#EAF4EF',
          subtle: '#F7FAF8',
          offwhite: '#F7FAF8',
          warm: '#FCFBF7',
          white: '#FFFFFF',
          border: '#D8E7E0',
          muted: '#64748B',
          text: '#10231E',
        },
        status: {
          success: 'var(--color-status-success)',
          'success-bg': 'var(--color-status-success-bg)',
          warning: 'var(--color-status-warning)',
          'warning-bg': 'var(--color-status-warning-bg)',
          error: 'var(--color-status-error)',
          'error-bg': 'var(--color-status-error-bg)',
          info: 'var(--color-status-info)',
          'info-bg': 'var(--color-status-info-bg)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        heading: ['var(--font-heading)'],
        serif: ['var(--font-serif)'],
      },
      maxWidth: {
        container: 'var(--container-max)',
        editorial: 'var(--container-editorial)',
        narrow: 'var(--container-narrow)',
      },
      borderRadius: {
        'healix-sm': 'var(--radius-sm)',
        'healix-md': 'var(--radius-md)',
        'healix-lg': 'var(--radius-lg)',
        'healix-xl': 'var(--radius-xl)',
        'healix-pill': 'var(--radius-pill)',
      },
      boxShadow: {
        'soft-sm': 'var(--shadow-level-1)',
        'soft-md': 'var(--shadow-level-2)',
        'soft-lg': 'var(--shadow-level-3)',
        'soft-xl': 'var(--shadow-level-4)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        drawer: 'var(--z-drawer)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
      },
    },
  },
  plugins: [],
}
